# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger on every successful release
on:
  pull_request:
    types: [closed]
    branches:
      - dev

concurrency:
    group: npm-publish

# Job will run on a ubuntu instance
jobs:
  build:
    if: (github.event.pull_request.merged == true && github.head_ref == 'release-staging')
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'lib/msal-core/src/package.json'
            common: 
              - 'lib/msal-common/src/package.json'
            browser: 
              - 'lib/msal-browser/src/package.json'
            node:
              - 'lib/msal-node/src/package.json'
            angular:
              - 'lib/msal-angular/src/package.json'
            react:
              - 'lib/msal-react/src/package.json'
            node-extensions:
              - 'extensions/msal-node-extensions/package.json'
          list-files: json

 
      - name: Get release date
        id: release-date
        run: |
          echo "::set-output name=date::$(node release-scripts/release_date.js -branch)"


      - name: Echo branch
        run: echo "${{ steps.release-date.outputs.date }} Release"


      # Create Pull Request from Post-release to dev- containing the package lock and cdn README updations
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Post-release
          branch: "${{ steps.release-date.outputs.date }}-post-release" 
          title: "Post release"
          body: |
            This PR contains package lock updates & cdn README updates for msal-browser and msal-core.
          draft: false