# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger on every release get created
on:
  push:
      branches:
      - master

# Job will run on a ubuntu instance
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the code
    - uses: actions/checkout@v2
      # Setup node with version 12.x and NPM registry url

    - uses: actions/setup-node@v1
      with:
          node-version: '14.x'
          registry-url: "https://registry.npmjs.org"

    - uses: dorny/paths-filter@v2
      id: changes
      with:
          filters: |
            core:
              - 'lib/msal-core/**/**.!(md)'
            common: &common
              - 'lib/msal-common/**/**.!(md)'
            browser: &browser
              - *common
            node:
              - *common
            angular:
              - *browser
            react:
              - *browser
          list-files: json   

    - name: Printing changed services
      run: |
        for val in ${{ join(fromJson(steps.changes.outputs.changes), ' ') }}; do echo $val; done

      # Run  install to install project packages
    - run: |
              npm install
      #  to build the project
    - run: npm build
      # publish the files to NPM
    - run: npm publish --dry-run
