# Bump package version numbers and create a release branch
name: Automate Release

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
      
    steps:

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Extracting head branch of merged PR
      - id: head
        name: Extract Head Branch Name
        run: echo "set-output name=test::${{ github.head_ref }}"
      
      # Install node_modules 
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
            cache: 'npm'
      - run: npm ci

      # Beachball bump 
      - if: "!contains(github.head_ref, 'release')"
        name: bump package versions
        run: node node_modules/beachball/bin/beachball bump -b origin/dev --bumpDeps false && node release-scripts/updateVersion.js
  
      # Extracting base branch of merged PR
      - name: Step that prints name of pull request's base branch
        run: |
           echo "Pull request's base branch is: ${BASE_BRANCH}"
        env:
              BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'

      # Logging branch name values 
      - name: Echo out branch values
        run: | 
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
   
      # Create/update Pull Request
      - if: "!contains(github.head_ref, 'release')"
        name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Automated PR from release-staging to dev 
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@microsoft.com>
          branch: release-staging
          title: 'Creating PR From :release-staging for review' 
          body: |
            Release PR : This PR contains the changelogs and version bumps since the previous release. 
          draft: false


  update_master:
    needs: release
    name: Create PR from dev to master post release 
    runs-on: ubuntu-latest
    if: "contains(github.head_ref, 'release')"
    steps:

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      # Extracting head branch of merged PR 
      - name: Extract Head Branch Name
        run: echo "BRANCH=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV

      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      # Create Pull Request from dev to master for sync post-publish
      - name: Create Pull Request
        if: >-  
            ${{
            github.event.pull_request.merged == true &&
            (
              contains(github.head_ref, 'release')
            )
            }}
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: PR:dev->master post release 
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@microsoft.com>
          branch: dev
          base: master
          title: 'Creating PR From :dev to master post release' 
          body: |
            Master-dev sync PR : This PR aims to bring main up-to-date with latest dev changes post successful publish. 
          draft: false
