# Bump package version numbers and create a release branch
name: Automate Release

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.head_ref, 'release')
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    env:
      BEACHBALL: 1

    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install node_modules
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install beachball
        run: npm ci

      # Beachball bump
      - name: bump package versions
        run: node node_modules/beachball/bin/beachball bump -b origin/dev --bumpDeps false && node release-scripts/updateVersion.js

      - run: |
              cd msal-browser
              mv package.json package.bak

      - name: update browserslist
        run: lerna exec "npx browserslist@latest --update-db"

      - run: |
              cd msal-browser
              mv package.bak package.json 

      - name: install npm 
        run: |
               rm -rf node_modules
               # Update just the lock file
               npm i --package-lock-only

      # Create/update Pull Request
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump package versions
          branch: release-staging
          title: "Next release"
          body: |
            Release PR : This PR contains the changelogs and version bumps for the next releases.
          draft: true
