# Bump package version numbers and create a release branch
name: Automate Release

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.head_ref, 'release')
    name: Bump versions and create changelogs
    runs-on: ubuntu-latest
    env:
      BEACHBALL: 1

    steps:
      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install node_modules
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install beachball
        run: npm ci

      # Beachball 
      - name: bump package versions
        run: node node_modules/beachball/bin/beachball bump -b origin/dev --bumpDeps false && node release-scripts/updateVersion.js

      - run: |
          cd lib/msal-browser
          mv package.json package.bak

      - name: update browserslist
        run: lerna exec "npx browserslist@latest --update-db"

      - run: |
          cd lib/msal-browser
          mv package.bak package.json

      - name: Get release date
        id: release-date
        run: echo "::set-output name=date::$(node release-scripts/getReleaseDate.js)"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get branch
        id: get-branch
        uses: actions/github-script@0.9.0
        with:
          script: |
            const branch = ${{ steps.date.outputs.date }}.replace(/\s+/g, '-')
            core.setOutput('branch', branch)

      # Create/update Pull Request
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump package versions
          branch: post-release-${{steps.get-id.outputs.branch}}
          title: "Release-${{ steps.date.outputs.date }}"
          body: |
            Release PR : This PR contains the changelogs and version bumps for the ${{ steps.month.outputs.month }} releases.
