# Bump package version numbers and create a release branch
name: Automate Release

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version '
        required: true
      versionCode:
        description: 'Version #'
        required: true

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Bump versions and create changelog PR --updation
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      
    steps:

      # Check-out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

  
      - id: step1
        name: Extract Head Branch Name
        run: echo "set-output name=test::${{ github.head_ref }}"
      
      - name: Echo out branch values
        run: | 
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
          
      - name: Get diff
        run: git diff ${{ github.head_ref }}...origin/dev
      
