# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger when Release PR from release-staging branch is merged into dev
on:
  pull_request:
    types: [closed]
    branches:
      - dev

  workflow_dispatch:
    inputs:
      libs:
        description: "Enter names of modified packages"
        required: false

# Job will run on a ubuntu instance
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'lib/msal-core/src/package.json'
            common: 
              - 'lib/msal-common/src/package.json'
            browser: 
              - 'lib/msal-browser/src/package.json'
            node:
              - 'lib/msal-node/src/package.json'
            angular:
              - 'lib/msal-angular/src/package.json'
            react:
              - 'lib/msal-react/src/package.json'
            node-extensions:
              - 'extensions/msal-node-extensions/package.json'
          list-files: json

      - name: Create Releases and Discussions
        run: |
          echo "Modified Packages: ${{ github.event.inputs.libs }}"
          (node ./.github/create-releases.js -${{ github.event.inputs.libs }})
