# NPM Publish is the name for this action
name: NPM Publish

# This action will trigger on every successful release
on:
  pull_request

# Job will run on a ubuntu instance
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        # Setup node with version 12.x and NPM registry url
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - name: build extensions
        run: |
          npm install
          npm run build

